### ISSUE TITLE
undefined behaviour in plugin handling

### ISSUE THREAD

**Issue by sgbeal** [tsa/vu8#1]
Hiya!

From Context.cpp:

```
void *sym = dlsym(dl, "vu8_module_init");
if (! sym) {
    return scope.Close(
        Throw("loadmodule: initialisation function not found"));
}
// g++ 3 is broken and can only handle a C-style cast for this
#if 0
v8::Handle<v8::Value> value =
    (*reinterpret_cast<Context::ModuleLoadCallback>(sym))();
#else
v8::Handle<v8::Value> value = ((Context::ModuleLoadCallback) sym)();
#endif
```

Casting to a function pointer that way relies on undefined behaviour. It is 99% likely to work on all modern platforms but is technically undefined. There are two portable workarounds that i know of, one for C (which will also work for the above case):

http://blog.s11n.net/?p=82

and one for C++:

http://wanderinghorse.net/computing/papers/#classloading_cpp

(disclosure: i wrote both of those pages)

**Comment by tsa** [comment]
I'm aware of this.

dlsym (and therefore dlsym support platforms) rely on this undefined behaviour. There is a POSIX report on the issue. When that is resolved I'll update the code.

**Comment by sgbeal** [comment]
Have you got a link to the Posix report? i'd be interested in reading it.

**Comment by tsa** [comment]
Found it on google.
