### ISSUE TITLE
Can the factory use primitive types?

### ISSUE THREAD

**Issue by swebb** [tsa/vu8#11]
I'm new to c++ templates and I'm struggling to understand the code.

Is it possible to create a factory such as Factory<float>? This gives the following error:

error: no matching function for call to 'FromV8(v8::Localv8::Value)'

What is the correct syntax?

Cheers.

Steve.

**Comment by tsa** [comment]
Yes it is possible to create such a factory:

``` c++
vu8::Factory<int>
```

for constructor that takes a single int.

**Comment by tsa** [comment]
Please attach your code to your query if you wish help with your error.
