### ISSUE TITLE
Reference to python2

### ISSUE THREAD

**Issue by djhopper01** [tsa/vu8#2]
There's a reference to python2. I was able to create a sym-link and avoid the error. I'm running python2.6 and it seems to work fine. It could be an issue specific to my machine, but just wanted to bring it to your attention. Thanks for the awesome project.

ln -s /usr/bin/python /usr/bin/python2

**Comment by insidewhy** [comment]
Removed this now.. you reconfigure it in cmake and "python" is the default. Sorry it took so long.
