### ISSUE TITLE
Docs "missing"

### ISSUE THREAD

**Issue by Meai** [tsa/vu8#3]
Hi, it would be helpful to know if I can return objects from c++ to javascript with this plugin too. And in general how vu8 is different/better than http://code.google.com/p/v8-juice

**Comment by insidewhy** [comment]
I've been updating the README file which displays on the github home page.

I'll add the information you request now, sorry for the wait.

**Comment by insidewhy** [comment]
Can you let me know what else you'd like added to the docs at https://github.com/nuisanceofcats/vu8 ?

Cheers!

**Comment by tsa** [comment]
Closing this issue but please re-open it if there's anything else you'd like me to add to the README or if you have any other comments.

Thank you!
